package hosts

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"
)

func TestRenderDeterministicAndPreservesUnrelatedContent(t *testing.T) {
	t.Parallel()
	current := []byte("# system entries\n127.0.0.1 localhost\n")
	wantBlock := BeginMarker + "\n" +
		"# Generated by portless; use the portless hosts operation to change this block.\n" +
		"127.0.0.1\tapi.localhost\n" +
		"::1\tapi.localhost\n" +
		"127.0.0.1\tfieldnotes.localhost\n" +
		"::1\tfieldnotes.localhost\n" +
		EndMarker + "\n"

	got, err := Render(current, []string{"FieldNotes.LocalHost.", "api.localhost", "api.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	want := string(current) + wantBlock
	if string(got) != want {
		t.Fatalf("rendered hosts file:\n%s\nwant:\n%s", got, want)
	}

	again, err := Render(got, []string{"fieldnotes.localhost", "API.LOCALHOST"})
	if err != nil {
		t.Fatal(err)
	}
	if string(again) != want {
		t.Fatalf("second render was not idempotent:\n%s", again)
	}

	cleaned, err := CleanContent(got)
	if err != nil {
		t.Fatal(err)
	}
	if string(cleaned) != string(current) {
		t.Fatalf("cleaned content = %q, want unrelated content %q", cleaned, current)
	}
}

func TestRenderReplacesBlockInPlace(t *testing.T) {
	t.Parallel()
	current := []byte("before\n" + BeginMarker + "\n127.0.0.1\told.localhost\n" + EndMarker + "\nafter\n")
	got, err := Render(current, []string{"new.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(got), "before\n"+BeginMarker+"\n") || !strings.HasSuffix(string(got), EndMarker+"\nafter\n") {
		t.Fatalf("managed block moved or unrelated content changed:\n%s", got)
	}
	if strings.Contains(string(got), "old.localhost") || !strings.Contains(string(got), "new.localhost") {
		t.Fatalf("managed entries were not replaced:\n%s", got)
	}
}

func TestCleanRecognizesCRLFManagedMarkers(t *testing.T) {
	t.Parallel()
	current := []byte("before\r\n" + BeginMarker + "\r\n127.0.0.1\told.localhost\r\n" + EndMarker + "\r\nafter\r\n")
	got, err := CleanContent(current)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "before\r\nafter\r\n" {
		t.Fatalf("cleaned CRLF content = %q", got)
	}
}

func TestRenderRejectsInvalidInput(t *testing.T) {
	t.Parallel()
	invalidNames := []string{
		"localhost",
		"example.com",
		"bad name.localhost",
		"bad\n127.0.0.1 injected.localhost",
		"-bad.localhost",
		"bad_.localhost",
		"bad.localhost:443",
	}
	for _, name := range invalidNames {
		if _, err := Render(nil, []string{name}); !errors.Is(err, ErrInvalidName) {
			t.Errorf("Render(%q) error = %v, want ErrInvalidName", name, err)
		}
	}

	malformed := [][]byte{
		[]byte(BeginMarker + "\n"),
		[]byte(EndMarker + "\n"),
		[]byte(BeginMarker + "\n" + BeginMarker + "\n" + EndMarker + "\n"),
		[]byte(BeginMarker + "\n" + EndMarker + "\n" + BeginMarker + "\n" + EndMarker + "\n"),
	}
	for _, content := range malformed {
		if _, err := Render(content, []string{"ok.localhost"}); !errors.Is(err, ErrMalformedBlock) {
			t.Errorf("Render malformed block error = %v, want ErrMalformedBlock", err)
		}
	}
}

func TestPlanIsReadOnlyAuditableAndStaleSafe(t *testing.T) {
	t.Parallel()
	config := testConfig(t, "127.0.0.1 localhost\n")
	plan, err := config.SynchronizePlan([]string{"app.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Lstat(config.LockPath); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("read-only plan created lock: %v", err)
	}
	if !plan.Changed || plan.Action != ActionSynchronize || plan.Path != config.Path ||
		plan.LockPath != config.LockPath || plan.UID != config.UID || plan.GID != config.GID || plan.Mode != config.Mode {
		t.Fatalf("plan is missing auditable mutation details: %+v", plan)
	}
	if plan.BeforeSHA256 == plan.AfterSHA256 || !strings.Contains(string(plan.DesiredContent()), "app.localhost") {
		t.Fatalf("plan does not describe desired content: %+v", plan)
	}

	desired := plan.DesiredContent()
	desired[0] = 'X'
	if plan.DesiredContent()[0] == 'X' {
		t.Fatal("DesiredContent exposed mutable plan storage")
	}

	if err := os.WriteFile(config.Path, []byte("127.0.0.1 localhost\n# external change\n"), config.Mode); err != nil {
		t.Fatal(err)
	}
	if _, err := config.Apply(plan); !errors.Is(err, ErrStalePlan) {
		t.Fatalf("Apply stale plan error = %v, want ErrStalePlan", err)
	}
	assertFileContent(t, config.Path, "127.0.0.1 localhost\n# external change\n")
}

func TestApplyExecutesExactPlan(t *testing.T) {
	t.Parallel()
	config := testConfig(t, "127.0.0.1 localhost\n")
	plan, err := config.SynchronizePlan([]string{"app.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	result, err := config.Apply(plan)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed {
		t.Fatal("Apply reported no change")
	}
	assertFileContent(t, config.Path, string(plan.DesiredContent()))
	assertMetadata(t, config.Path, config.Mode, config.UID, config.GID)
	assertMetadata(t, config.LockPath, 0o600, config.UID, config.GID)

	tampered, err := config.SynchronizePlan([]string{"app.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	tampered.Names = []string{"other.localhost"}
	if _, err := config.Apply(tampered); err == nil {
		t.Fatal("Apply accepted a plan with modified audit names")
	}
}

func TestSynchronizeAndCleanAreLockedIdempotentMutations(t *testing.T) {
	t.Parallel()
	base := "# unrelated\n127.0.0.1 localhost\n"
	config := testConfig(t, base)

	first, err := config.Synchronize([]string{"app.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	if !first.Changed {
		t.Fatal("first synchronization reported no change")
	}
	firstContent, err := os.ReadFile(config.Path)
	if err != nil {
		t.Fatal(err)
	}
	second, err := config.Synchronize([]string{"APP.LOCALHOST."})
	if err != nil {
		t.Fatal(err)
	}
	if second.Changed {
		t.Fatal("identical synchronization was not a no-op")
	}
	secondContent, err := os.ReadFile(config.Path)
	if err != nil {
		t.Fatal(err)
	}
	if string(firstContent) != string(secondContent) {
		t.Fatal("idempotent synchronization changed bytes")
	}
	assertMetadata(t, config.Path, config.Mode, config.UID, config.GID)
	assertMetadata(t, config.LockPath, 0o600, config.UID, config.GID)

	cleaned, err := config.Clean()
	if err != nil {
		t.Fatal(err)
	}
	if !cleaned.Changed {
		t.Fatal("clean reported no change")
	}
	assertFileContent(t, config.Path, base)
	again, err := config.Clean()
	if err != nil {
		t.Fatal(err)
	}
	if again.Changed {
		t.Fatal("second clean was not a no-op")
	}
}

func TestCheckAndMutationsRejectUnsafeFiles(t *testing.T) {
	t.Parallel()
	t.Run("hosts symlink", func(t *testing.T) {
		config := testConfig(t, "127.0.0.1 localhost\n")
		target := filepath.Join(t.TempDir(), "target")
		if err := os.WriteFile(target, []byte("untouched\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.Remove(config.Path); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(target, config.Path); err != nil {
			t.Fatal(err)
		}
		if _, err := config.Check(); err == nil {
			t.Fatal("Check accepted symlinked hosts file")
		}
		if _, err := config.Synchronize([]string{"app.localhost"}); err == nil {
			t.Fatal("Synchronize accepted symlinked hosts file")
		}
		assertFileContent(t, target, "untouched\n")
	})

	t.Run("unsafe hosts mode", func(t *testing.T) {
		config := testConfig(t, "127.0.0.1 localhost\n")
		if err := os.Chmod(config.Path, 0o666); err != nil {
			t.Fatal(err)
		}
		if _, err := config.Check(); err == nil || !strings.Contains(err.Error(), "unsafe mode") {
			t.Fatalf("Check unsafe mode error = %v", err)
		}
		if _, err := config.Synchronize([]string{"app.localhost"}); err == nil {
			t.Fatal("Synchronize accepted group/world-writable hosts file")
		}
	})

	t.Run("wrong owner", func(t *testing.T) {
		config := testConfig(t, "127.0.0.1 localhost\n")
		config.UID++
		if _, err := config.Check(); err == nil || !strings.Contains(err.Error(), "is owned by") {
			t.Fatalf("Check wrong owner error = %v", err)
		}
	})

	t.Run("lock symlink", func(t *testing.T) {
		config := testConfig(t, "127.0.0.1 localhost\n")
		target := filepath.Join(t.TempDir(), "lock-target")
		if err := os.WriteFile(target, nil, 0o600); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(target, config.LockPath); err != nil {
			t.Fatal(err)
		}
		if _, err := config.Synchronize([]string{"app.localhost"}); err == nil {
			t.Fatal("Synchronize accepted symlinked lock")
		}
	})

	t.Run("unsafe lock mode", func(t *testing.T) {
		config := testConfig(t, "127.0.0.1 localhost\n")
		if err := os.WriteFile(config.LockPath, nil, 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := config.Synchronize([]string{"app.localhost"}); err == nil || !strings.Contains(err.Error(), "unsafe mode") {
			t.Fatalf("Synchronize unsafe lock error = %v", err)
		}
		assertMetadata(t, config.LockPath, 0o644, config.UID, config.GID)
	})
}

func TestCheckIsReadOnly(t *testing.T) {
	t.Parallel()
	config := testConfig(t, "127.0.0.1 localhost\n")
	preflight, err := config.Check()
	if err != nil {
		t.Fatal(err)
	}
	if !preflight.Hosts.Exists || preflight.Lock.Exists {
		t.Fatalf("unexpected preflight: %+v", preflight)
	}
	if _, err := os.Lstat(config.LockPath); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Check mutated lock path: %v", err)
	}
}

func TestSynchronizeWaitsForRealProcessLock(t *testing.T) {
	if os.Getenv("PORTLESS_HOSTS_LOCK_HELPER") == "1" {
		lockHelperProcess(t)
		return
	}
	config := testConfig(t, "127.0.0.1 localhost\n")
	command := exec.Command(os.Args[0], "-test.run=^TestSynchronizeWaitsForRealProcessLock$")
	command.Env = append(os.Environ(),
		"PORTLESS_HOSTS_LOCK_HELPER=1",
		"PORTLESS_HOSTS_LOCK_PATH="+config.LockPath,
		"PORTLESS_HOSTS_LOCK_UID="+strconv.Itoa(config.UID),
		"PORTLESS_HOSTS_LOCK_GID="+strconv.Itoa(config.GID),
	)
	stdout, err := command.StdoutPipe()
	if err != nil {
		t.Fatal(err)
	}
	stdin, err := command.StdinPipe()
	if err != nil {
		t.Fatal(err)
	}
	command.Stderr = os.Stderr
	if err := command.Start(); err != nil {
		t.Fatal(err)
	}
	if line, err := bufio.NewReader(stdout).ReadString('\n'); err != nil || line != "locked\n" {
		t.Fatalf("lock helper readiness = %q, %v", line, err)
	}

	releaseAfter := 200 * time.Millisecond
	go func() {
		time.Sleep(releaseAfter)
		stdin.Close()
	}()
	started := time.Now()
	result, err := config.Synchronize([]string{"locked.localhost"})
	if err != nil {
		t.Fatal(err)
	}
	if elapsed := time.Since(started); elapsed < releaseAfter/2 {
		t.Fatalf("Synchronize did not wait for process lock: %v", elapsed)
	}
	if !result.Changed {
		t.Fatal("synchronization after lock release reported no change")
	}
	if err := command.Wait(); err != nil {
		t.Fatal(err)
	}
}

func lockHelperProcess(t *testing.T) {
	t.Helper()
	uid, err := strconv.Atoi(os.Getenv("PORTLESS_HOSTS_LOCK_UID"))
	if err != nil {
		t.Fatal(err)
	}
	gid, err := strconv.Atoi(os.Getenv("PORTLESS_HOSTS_LOCK_GID"))
	if err != nil {
		t.Fatal(err)
	}
	config := Config{LockPath: os.Getenv("PORTLESS_HOSTS_LOCK_PATH"), UID: uid, GID: gid}
	lock, err := config.lock()
	if err != nil {
		t.Fatal(err)
	}
	defer lock.Close()
	fmt.Println("locked")
	if _, err := os.Stdin.Read(make([]byte, 1)); err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, os.ErrClosed) {
		t.Fatal(err)
	}
}

func testConfig(t *testing.T, content string) Config {
	t.Helper()
	directory := t.TempDir()
	path := filepath.Join(directory, "hosts")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(path, 0o644); err != nil {
		t.Fatal(err)
	}
	return Config{
		Path:     path,
		LockPath: filepath.Join(directory, "hosts.lock"),
		UID:      os.Geteuid(),
		GID:      os.Getegid(),
		Mode:     0o644,
	}
}

func assertFileContent(t *testing.T, path, want string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != want {
		t.Fatalf("%s content = %q, want %q", path, content, want)
	}
}

func assertMetadata(t *testing.T, path string, mode os.FileMode, uid, gid int) {
	t.Helper()
	state, _, err := inspectRegular(path, mode, uid, gid, false)
	if err != nil {
		t.Fatal(err)
	}
	if !state.Exists || state.Mode != mode || state.UID != uid || state.GID != gid {
		t.Fatalf("unexpected metadata for %s: %+v", path, state)
	}
}
